# Add these options at the top level of your cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$REPO_NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'TELEGRAM_BOT_TOKEN=${_TELEGRAM_BOT_TOKEN},WEBHOOK_URL=${_WEBHOOK_URL},OPENAI_API_KEY=${_OPENAI_API_KEY}, ASSISTANT_ID=${_ASSISTANT_ID}, THREAD_ID=${_THREAD_ID}, MONGODB_URI=${_MONGODB_URI}, SENDGRID_API_KEY=${_SENDGRID_API_KEY}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'services'
    - 'add-iam-policy-binding'
    - '$REPO_NAME'
    - '--region=us-central1'
    - '--member=allUsers'
    - '--role=roles/run.invoker'

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'

# Define substitutions with dummy values
substitutions:
  _TELEGRAM_BOT_TOKEN: 'dummy-token'
  _WEBHOOK_URL: 'dummy-url'
  _OPENAI_API_KEY: 'dummy-key'
  _ASSISTANT_ID: 'dummy-id'
  _THREAD_ID: 'dummy-id'
  _MONGODB_URI: 'dummy-uri'
  _SENDGRID_API_KEY: 'dummy-key'
