steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$REPO_NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'TELEGRAM_API_ID=$$TELEGRAM_API_ID,TELEGRAM_API_HASH=$$TELEGRAM_API_HASH,TELEGRAM_BOT_TOKEN=$$TELEGRAM_BOT_TOKEN,WEBHOOK_URL=$$WEBHOOK_URL,OPENAI_API_KEY=$$OPENAI_API_KEY'
    secretEnv: ['TELEGRAM_API_ID', 'TELEGRAM_API_HASH', 'TELEGRAM_BOT_TOKEN', 'WEBHOOK_URL', 'OPENAI_API_KEY']

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/TELEGRAM_API_ID/versions/latest
      env: 'TELEGRAM_API_ID'
    - versionName: projects/$PROJECT_ID/secrets/TELEGRAM_API_HASH/versions/latest
      env: 'TELEGRAM_API_HASH'
    - versionName: projects/$PROJECT_ID/secrets/TELEGRAM_BOT_TOKEN/versions/latest
      env: 'TELEGRAM_BOT_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/WEBHOOK_URL/versions/latest
      env: 'WEBHOOK_URL'
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: 'OPENAI_API_KEY'
